services:
  auth-service:
    image: emrecerrah/auth-service-all-in-one
    ports:
      - "8090:8090"
    environment:
      SERVICE_PORT: 8090
      SPRING_DATASOURCE_DB_NAME: mydatabase
      SPRING_DATASOURCE_USERNAME: psql
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET_KEY: super-secret
      JWT_EXPIRATION_MS: 300000
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: strong-password
      ADMIN_EMAIL: admin@mycompany.com
