version : "3"
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: Postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=psql
    ports:
      - '5432:5432'
#  zipkin:
#    image: 'openzipkin/zipkin:latest'
#    ports:
#      - '9411'
