
###### Server port ########

server:
  port: 8090  # ${SERVICE_PORT}

###### Spring configs ########
spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://http://localhost:27017/authservice #mongodb://admin:password@localhost:27017/baeldung

springdoc:
  swagger-ui:
    path: /swagger-ui.html

######## JWT configs ########
AuthService:
  secret:
    key: key
    issuer: EmreCerrah
    date: 300000    # 1000L * 60 * 5

