server:
  port: ${SERVICE_PORT:8090}  # Varsayılan 8090

spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: psql  #postgres
    password: postgres

  zipkin:
    base-url: http://localhost:9411

springdoc:
  swagger-ui:
    path: /swagger-ui.html

AuthService:
  secret:
    key: ${JWT_SECRET_KEY:key}
    issuer: ${JWT_ISSUER:EmreCerrah}
    expirationMs: ${JWT_EXPIRATION_MS:300000}

  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}
    email: ${ADMIN_EMAIL:admin@example.com}