CREATE TABLE role
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name SMALLINT,
    CONSTRAINT pk_role PRIMARY KEY (id)
);


CREATE TABLE auth
(
    id       UUID         NOT NULL,
    username VARCHAR(40)  NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(80)  NOT NULL,
    createAt TIMESTAMP WITHOUT TIME ZONE  NOT NULL,
    updateAt TIMESTAMP WITHOUT TIME ZONE  NOT NULL,
    state BOOLEAN  NOT NULL,
    CONSTRAINT pk_auth PRIMARY KEY (id)
);

CREATE TABLE auth_roles
(
    auth_id UUID    NOT NULL,
    role_id INTEGER NOT NULL,
    CONSTRAINT pk_auth_roles PRIMARY KEY (auth_id, role_id)
);

ALTER TABLE auth
    ADD CONSTRAINT uc_auth_email UNIQUE (email);

ALTER TABLE auth
    ADD CONSTRAINT uc_auth_username UNIQUE (username);

ALTER TABLE auth_roles
    ADD CONSTRAINT fk_autrol_on_auth FOREIGN KEY (auth_id) REFERENCES auth (id);

ALTER TABLE auth_roles
    ADD CONSTRAINT fk_autrol_on_role FOREIGN KEY (role_id) REFERENCES role (id);